version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortener-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 12345
    networks:
      - shortener-network

  app:
    build: .
    container_name: shortener-app
    ports:
      - "8080:8080"
    environment:

      DB_URL_PROD: jdbc:postgresql://postgres:5432/shortener
      DB_USER: postgres
      DB_PASSWORD: 12345

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 12345

      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - postgres
      - redis
    networks:
      - shortener-network

volumes:
  postgres_data:

networks:
  shortener-network:
    driver: bridge