version: '3.8'

services:
  app:
    image: theguibsantos/high-performance-url-shortener:latest
    container_name: shortner_app
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL_PROD: jdbc:postgresql://postgres:5432/shortener
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    networks:
      - shortner-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: shortner
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - shortner-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - shortner-network

volumes:
  postgres_data_prod:

networks:
  shortner-network:
    driver: bridge